services:
  backend:
    build: ./backend
    container_name: django-backend
    expose:
      - "8000"
    volumes:
      - ./backend:/app          # монтируем всю папку backend (включая media)
      - backend_data:/app/data
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "127.0.0.1:8090:80"   # только для хостового nginx (80/8080 заняты nginx и Pterodactyl)
    volumes:
      - ./backend/media:/app/media   # монтируем папку media из backend в nginx
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_data: